[build]
  command = "npm install && npm run build"
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  
  [functions.timeout]
  default = 30  # Timeout default 30 detik

[functions.process-document]
  timeout = 30  # Timeout khusus untuk process-document

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true