[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "public"

# Versi Node.js digunakan di Netlify melalui file `.nvmrc` atau di environment, bukan dari toml.[build]
  functions = "netlify/functions"
  publish = "public"

[dev]
  functions = "netlify/functions"
# Jadi 'NODE_VERSION = "18"' dihapus karena tidak valid di bagian ini.

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "@supabase/supabase-js",
    "@google/generative-ai",
    "googleapis",
    "dotenv"
  ]

# Redirect API ke Functions (contoh: /api/chat → /.netlify/functions/chat)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200