[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  timeout = 30 # Timeout global 30 detik

[functions."process-document"]
  timeout = 30 # Timeout khusus untuk process-document

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200